name: Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x
      - name: Restore and Build
        run: |
          dotnet restore LoggerLite.EventLog/LoggerLite.EventLog.csproj
          dotnet build LoggerLite.EventLog/LoggerLite.EventLog.csproj --no-restore -c Release
      - name: Pack
        run: dotnet pack LoggerLite.EventLog/LoggerLite.EventLog.csproj --no-build -c Release -o nupkgs
      - name: Login to NuGet
        uses: NuGet/login@v1
        with:
          usernameVar: NUGET_USER
          tokenVar: NUGET_TOKEN
      - name: Push to NuGet
        run: dotnet nuget push nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate
